### ISSUE TITLE
Add ODM2/YODA-Tools

### ISSUE THREAD

**Issue by emiliom** [ODM2/conda-recipes-ODM2#12]
From @valentinedwv over at [ODM2PythonAPI/issue 49](https://github.com/ODM2/ODM2PythonAPI/issues/49#issuecomment-207613004):

> For [YodaTools](https://github.com/ODM2/YODA-Tools), can you add this package to conda: `valideer`

Dave, is YODA-Tools in good shape for preparing a conda package? It doesn't look that way to me. Or are you just asking to have `valideer`, not YODA-Tools, added to the ODM2 anaconda channel, for now, b/c it would help you with YODA-Tools development? I assume it's the latter, which seems much easier.

**Comment by ocefpaf** [comment]
Coming back to this... `valideer` was already added: https://github.com/ODM2/conda-recipes-ODM2/pull/11

If there are any other tools from the TodaTools stack that have a `setup.py` and/or are uploaded to `PyPI` I can start adding them immediately to the channel.

**Comment by emiliom** [comment]
Let's set this aside, actually. YodaTools is being actively worked on now, and a substantial refactor may be involved. Let's wait for the dust to settle on that before putting any work on packaging.

**Comment by ocefpaf** [comment]
We added `valideer` and Yoda tools is listed in #1. Closing this a duplicated.

**Comment by emiliom** [comment]
Sure. We can open a new issue when a request comes in to create a conda package for it. Possibly in the next month or two.
