### ISSUE TITLE
Failing build: odm2api

### ISSUE THREAD

**Issue by ocefpaf** [ODM2/conda-recipes-ODM2#13]
The builds are failing because the tag disappeared. I guess we should delete the binaries and use the new tag.

https://github.com/ODM2/ODM2PythonAPI/releases

**Comment by emiliom** [comment]
Yes ... I had asked for / suggested that change in the tag around Monday, and it was silently implemented today, apparently.

**Comment by ocefpaf** [comment]
No problem. I just updated the recipe.

PS: The group is small and the package is new, so no harm was done. But in the future I recommend issuing a new tag and leaving the old one there.

**Comment by emiliom** [comment]
> PS: The group is small and the package is new, so no harm was done. But in the future I recommend issuing a new tag and leaving the old one there.

Will do. Thanks for the tip.
