### ISSUE TITLE
Transfer this repository to ODM2

### ISSUE THREAD

**Issue by ocefpaf** [ODM2/conda-recipes-ODM2#2]
Ping @emiliom should we do that?

**Comment by emiliom** [comment]
Ultimately, yes. If it makes things any easier for you during the first steps, I see no problem keeping it here for now.

I have admin rights on the ODM2 organization, so I can help make the transfer.

**Comment by emiliom** [comment]
The recipes iphreeqc and phreeqpy should go somewhere else, not in ODM2 (they don't revolve around ODM2). As I've mentioned, eventually we'll want to create a "BiGCZ" anaconda channel as well, broader than -- but encompassing -- ODM2. That's where they should go. I can create a conda-recipes repo at https://github.com/BiG-CZ/ and we can park those recipes there.

**Comment by ocefpaf** [comment]
> Ultimately, yes. If it makes things any easier for you during the first steps, I see no problem keeping it here for now.

It does not make my job harder nor easier. I just think it should be there. I will give you access here too just in case.

> The recipes iphreeqc and phreeqpy should go somewhere else

Sure. Nothing is getting build now. I will ping you before we create the channel.

**Comment by emiliom** [comment]
> > The recipes iphreeqc and phreeqpy should go somewhere else
> 
> Sure. Nothing is getting build now. I will ping you before we create the channel.

Creating a BiGCZ channel is down the road. Getting some packages built and tested on the ODM2 channel is more important at this stage. But I've created a conda-recipes repo at https://github.com/BiG-CZ/conda-recipes, just as a parking place for `iphreeqc` and `phreeqpy` for now. Feel free to move them there and forget about them for a while! I gave you full rights on that repo.

**Comment by ocefpaf** [comment]
The channel is being populated now. I created all `TOKENS` using my account and pointing to this repository. Once you OK with the channel and get some free time we can do the transfer and re-issue the `TOKENS`.

(I will leave this issue open as the transfer will happen eventually.)

**Comment by emiliom** [comment]
Awesome, thanks!! I can see the packages on the channel.

I noticed that the conda package has the same name as the github repo, "ODM2PythonAPI". As you may recall, for building Python packages we're using the package name "odm2api". Can we do that with the conda package, so its name is `odm2api`? I'd really prefer that.

I can help do the transfer today, or wait till we've stabilized how we're doing things on this repo and the ODM2 anaconda channel. Whatever you think is less complicated and less work for both of us.

**Comment by ocefpaf** [comment]
> Can we do that with the conda package, so its name is `odm2api`?

Sure. I assumed the repository name was the same as the package name.

> I can help do the transfer today, or wait till we've stabilized how we're doing things on this repo and the ODM2 anaconda channel. Whatever you think is less complicated and less work for both of us.

Now that I created the TOKENS let's populate it first and transfer later once things are stable.

**Comment by emiliom** [comment]
> Now that I created the TOKENS let's populate it first and transfer later once things are stable.

Sounds good.

**Comment by emiliom** [comment]
Are we at a good point to transfer the repo to https://github.com/ODM2? It's fine with me either way -- doing it now or waiting a bit longer.

BTW, I was able to install `odm2api` from the channel via `conda install -c https://conda.anaconda.org/odm2 odm2api`. Very cool to see that we're there!

**Comment by ocefpaf** [comment]
> Are we at a good point to transfer the repo to https://github.com/ODM2? 

Here is we need to do:
- [ ] move this repository to ODM2;
- [ ] enable Travis-CI, AppVeyor and CircleCI in the repository with an admin account or a bot account just for that purpose;
- [ ] re-encrypt the TOKEN with Travis-CI CLI tool, AppVeyor and CicrcleCI webservices;
- [ ] update the CI files: `.travis.yml` and `appveyor.yml`.

The first one and last steps are easy. The second one you must decide if someone will the the adim or if you want to create a dummy bot account for that. (We have a bot account on `conda-forge` and `ioos` and we add people as part of the team so they don't need to log in with the bot account.) I will probably need to guide you on the third step (the encryption), but we can do that over a Google Hangout/Skype session.

**Comment by emiliom** [comment]
Thanks for laying out the steps. Let's leave it for early next week, then. Probably Tuesday.

**Comment by ocefpaf** [comment]
> Thanks for laying out the steps. Let's leave it for early next week, then. Probably Tuesday.

Sure. Ideally we should do that ASAP to avoid basing things off my username and accounts.

**Comment by emiliom** [comment]
>  Ideally we should do that ASAP to avoid basing things off my username and accounts.

Got it. We'll shoot for Tuesday at the very latest, possibly Monday.

**Comment by emiliom** [comment]
Let's try to do the repository transfer today (Wednesday) after 11:30 am PDT, if that works for you.

In the meantime, can you tell me more about this:

> enable Travis-CI, AppVeyor and CircleCI in the repository with an admin account or a bot account just for that purpose; .... you must decide if someone will be the adim or if you want to create a dummy bot account for that. (We have a bot account on conda-forge and ioos and we add people as part of the team so they don't need to log in with the bot account.)

I think Travis-CI and AppVeyor have already been enabled at the ODM2 organization level.

**Comment by ocefpaf** [comment]
> Let's try to do the repository transfer today (Wednesday) after 11:30 am PDT, if that works for you.

Works for me.

> I think Travis-CI and AppVeyor have already been enabled at the ODM2 organization level.

You will need to autorize those for the `conda-recipes-ODM2` once we transfer.

Edit: You will need to install Travis-CI CLI: https://github.com/travis-ci/travis.rb#installation

**Comment by emiliom** [comment]
> Edit: You will need to install Travis-CI CLI: https://github.com/travis-ci/travis.rb#installation

Thanks. I had to update ruby (FYI, I'm on Ubuntu). Then, when I tried to install the Travis-CI CLI, it failed. I'll try it again later.

**Comment by ocefpaf** [comment]
@emiliom if you are OK giving me adim rights in at `ODM2/conda-recipes-ODM2` I can do all that.

**Comment by emiliom** [comment]
Absolutely!

I'll be driving for the next hour. Let me know how to go about creating
ODM2/conda-recipes-ODM2. Do I create a new, blank repo? Fork your repo? Use
a magic wand?

**Comment by ocefpaf** [comment]
If you add me to ODM2 I can do that directly from here. Otherwise you can fork it there and, when I delete it here that copy will become the canonical one.

**Comment by emiliom** [comment]
I created a new ODM2 Admin group and added you to it with Owner privileges. (BTW, I cancelled the first invitation I sent you). Hopefully that's all you need.

**Comment by ocefpaf** [comment]
Done!

**Comment by emiliom** [comment]
Wow! Thanks.

So, do you still need me for anything to complete the transfer (the 4 steps you listed last week)? It looks like you're 100% done, since you closed this issue. Or, at least you don't need me anymore, which is just as good :)

**Comment by ocefpaf** [comment]
I opened #24 to keep track of the rest. I believe I can do that with my new powers :wink:

**Comment by emiliom** [comment]
Great!
