### ISSUE TITLE
Refresh TOKENs

### ISSUE THREAD

**Issue by ocefpaf** [ODM2/conda-recipes-ODM2#24]
Re-encrypt and point them to the new repository.
- [X] AppVeyor
- [X] CircleCI
- [X] Travis-CI

**Comment by ocefpaf** [comment]
@emiliom I could access `Travis-CI`, but `AppVeyor` and `Circle` do not let me create accounts pointing to this repo as _owner_ :unamused: 

Can you do it as _admin_?
- https://www.appveyor.com/
- https://circleci.com/

**Comment by emiliom** [comment]
So, what exactly are you asking me to do? And what do you mean by `admin`? I created a new group called `admin` and included you in it, then gave you `owner` privileges. But there is also an older `owners` group that github now discourages, which has `owner` privileges (I think).

**Comment by ocefpaf** [comment]
I had to change the _admin_ team from _Read_ to _Admin_ :wink: Then I was able to delete two webhooks (from `AppVeyor` and `CircleCI`) that were inherited from my account but would not work here as we transferred the repository

I was also able to activate `CircleCI`, but I am still struggling with `AppVeyor`. (Pity that `CircleCI` and `AppVeyor` are as smart as `Travis-CI`.)

BTW I still encourage you to create accounts on `CircleCI` and `AppVeyor` (I am assuming you already have a `Travis-CI` account). You can login with your GitHub account.  Once you do let me know and I can add you as a "team member", so you can to view the CIs activity, cancel, restart builds, etc.

**Comment by emiliom** [comment]
Thanks! Frankly, I'm total newbie to all these CI tools. My intent is that once we've reached a good stable point with the ODM2 channel, I'd like to have a Google Hangout session with you to give me a crash introduction to these tools, and have an opportunity to ask questions. I suspect others in the ODM2 team will be interested in joining, too. I can then follow your recommendation to create my accounts as needed.

**Comment by ocefpaf** [comment]
> Thanks! Frankly, I'm total newbie to all these CI tools.

We all are. They keep changing. It is such a moving target that I have to re-learn it every time I need to set it up.

> My intent is that once we've reached a good stable point with the ODM2 channel, I'd like to have a Google Hangout session with you to give me a crash introduction to these tools, and have an opportunity to ask questions. I suspect others in the ODM2 team will be interested in joining, too.

Sure!

> I can then follow your recommendation to create my accounts as needed.

We will need that for AppVeyor, I believe that `CircleCI` and `Travis-CI` are smarter and you, as a team member of this repo, already have access.

**Comment by ocefpaf** [comment]
I believe I got AppVeyor working. I had to unauthorized and then re-unauthorized is on my account for the repo to show up in the list. Go figure...

Tomorrow I'll test a complete workflow of PR/Build/Upload.

**Comment by emiliom** [comment]
> Tomorrow I'll test a complete workflow of PR/Build/Upload.

Otimo!

**Comment by emiliom** [comment]
> Tomorrow I'll test a complete workflow of PR/Build/Upload.

Were you able to test the workflow? Just curious.

**Comment by ocefpaf** [comment]
Yep. Everything is in working conditions. We need more modules/packages to add now! I already did all that had a `setup.py` :wink:

**Comment by emiliom** [comment]
Awesome! I've asked the group to help prioritize other modules
