### ISSUE TITLE
Add odm2djangoadmin

### ISSUE THREAD

**Issue by emiliom** [ODM2/conda-recipes-ODM2#27]
https://github.com/miguelcleon/odm2djangoadmin

@miguelcleon is the developer of this terrific ODM2-based tool (a web-based UI to an ODM2 PostgreSQL database, using Django). @ocefpaf (Filipe), three of us ODM2 leads had a great conference call with Miguel earlier today, where he demo'd `odm2djangoadmin`. I offered for you and I (mostly you, of course) to work with him to help him package `odm2djangoadmin` and then create a conda package on the [odm2 anaconda channel](https://anaconda.org/odm2/). I said we'd start connecting early next week, and made it clear that we'll be asking him to do some work in tweaking his repo to make it more readily installable. He's on board.

As additional background, a couple of weeks ago Miguel shared this (edited from an email of his):

> graphs for soils data I’ve developed
> http://lczodata.com/ODM2/ODM2CZOData/chartVariableAndFeature.html
> 
> We have about 2.4 million data values now in our ODM2 database and over 11,000 soil measurements.

EDIT: Here's the [presentation Miguel gave us today](https://drive.google.com/file/d/0B8sRQJ2uLIjceXVwZnQ4QksyZm8/view?usp=sharing)

**Comment by miguelcleon** [comment]
Yes, sounds good. Let me know how we should get started.

**Comment by emiliom** [comment]
Thanks, @miguelcleon. @ocefpaf, the first step will be to get the repository/"module" in order for packaging. Can you take a look at Miguel's repository, and work with him to advise him on what steps to take, and/or implement some of those steps via a fork? Miguel, please correct me if I'm wrong, but it sounded like you could use help with expertise on how to best organize the repo and set up packaging configurations.

Filipe, there's no specific rush on this. Slow and steady progress is totally fine. The pace will depend at least in part of your respective availabilities and how much work will be needed to get the repo/module in order.

Thanks to both! This will be exciting.

**Comment by miguelcleon** [comment]
Yes, that would be great, I would certainly appreciate help with that.

**Comment by emiliom** [comment]
@ocefpaf, I'll be traveling and pretty busy (therefore not very responsive) for the next two weeks.

Working on packaging odm2djangoadmin can be your main priority for ODM2/BiGCZ work in the next two weeks (we can talk offline about overall priorities, if any). I realize that just familiarizing yourself with how things are organized and what's needed to get it ready for packaging will take some time, so that's perfect :) Also, @miguelcleon will be away for about 10 days starting tomorrow, probably not answering emails. If you can ask him questions today that may be helpful, but I realize that's very little lead time, so no worries if you can't.

**Comment by ocefpaf** [comment]
@emiliom It seems that all the messages from this repo slipped under the radar. (Since conda-forge started I am getting +100 e-mail per day.)

I will start this ASAP.

**Comment by miguelcleon** [comment]
thanks felipe, I will likely still be able to answer emails, although likely at a slower pace then usual. I'll be away starting tomorrow returning to the office on May 9th.

**Comment by ocefpaf** [comment]
No problem @miguelcleon. Thanks!

**Comment by emiliom** [comment]
> +100 e-mail per day
> Yikes. Looks like you need a conda-forge filter :grimacing:

Thanks to both.

**Comment by ocefpaf** [comment]
PR https://github.com/miguelcleon/ODM2-Admin/pull/102 was not merged and I believe the devs chose only the Dockerimage route. Closing this but we can reopen if the need for a adm2adim packages arises.

**Comment by emiliom** [comment]
Sounds good.

**Comment by miguelcleon** [comment]
agreed, a docker image seems like the best route for this.
