### ISSUE TITLE
ODM2PythonAPI status

### ISSUE THREAD

**Issue by emiliom** [ODM2/conda-recipes-ODM2#3]
FYI, about the [ODM2PythonAPI package](https://github.com/ODM2/ODM2PythonAPI/):
- We haven't created (pre)releases yet. We had a discussion about it on Friday, with pro and con opinions. Hopefully this coming week we'll create a first pre-release, taken from master.
- Another group in our distributed team has started exploring creating a pypi package. Currently in testing at https://testpypi.python.org/pypi/odm2api. I'm not sure yet if the conda recipe should shoot for using that vs a tagged pre-release on the github repo; I think I prefer the latter, _for now_.
- There's been a lot of overhauls and cleanups in the last two month and a half, currently all in branches. No timeline yet for merging into master.

**Comment by ocefpaf** [comment]
No problem. I am testing the build machinery against the [latest commit](https://github.com/ODM2/ODM2PythonAPI/commit/2e85ebada2af26386b49374e61b2d448d2d8cd6e), as soon as there is a release we update the package to reflect that.

Regarding PyPI vs GitHub releases. I recommend to keep them in sync to avoid confusion. If that is done properly it does not really matter where the conda recipe is getting the source.

**Comment by emiliom** [comment]
> No problem. I am testing the build machinery against the latest commit, as soon as there is a release we update the package to reflect that.

As I mentioned, there's now a tagged pre-release, and we're getting around to a more deliberate strategy for releases. So I think that will be the way to go for the near future.

> Regarding PyPI vs GitHub releases. I recommend to keep them in sync to avoid confusion. 

Agreed in principle. In practice, for the near future (next month or so), the PyPI effort will be independent and possibly less predictable. So, for the anaconda channel, let's use github releases for now.

**Comment by ocefpaf** [comment]
> So, for the anaconda channel, let's use github releases for now.

I will follow that then.

**Comment by ocefpaf** [comment]
I am using the GitHub tags to be closer the ODM2 group releases of `odm2api`.
