### ISSUE TITLE
Example CI build and test scripts for a project

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/conda-recipes-ODM2#31]
> Can we do a proto travis scripts to pull the conda distribution so that we could use them for testing and development... aka dogfood.

We can. I can send a PR your way or point to an example.

> Then maybe we can incorporate this into other travis scripts.

Which would be the first repository to use it?

@valentinedwv, can you open a separate issue for this? I'd like to keep this issue focused on just documentation on how the process works. If what you and @ocefpaf end up doing is relevant to how the conda recipes & packages are created and updated, then it'll be great to have notes from that process added here. Thanks.

**Comment by valentinedwv** [comment]
Suggest for repository be WofPy. It contains modules both independent, and dependent of ODM2Api.
Uses only sqlalchemy

**Comment by valentinedwv** [comment]
>  If what you and @ocefpaf end up doing is relevant to how the conda recipes & packages are created and updated, then it'll be great to have notes from that process added here. Thanks.

This would be once we get pieces of the stack green, would be to enable them, and move push to anaconda to an 
`after_success:`

https://docs.travis-ci.com/user/deployment/custom/

**Comment by ocefpaf** [comment]
See https://github.com/ODM2/WOFpy/pull/65

**Comment by ocefpaf** [comment]
WOFpy is already using ODM2 conda channel and Travis-CI and there is a PR for odm2api and odm2adim. I believe we can close this issue. Please let me know if you have any questions on the matter.
