### ISSUE TITLE
conda packages, Desktop apps, simple installs, and ODM2StreamingDataLoader

### ISSUE THREAD

**Issue by emiliom** [ODM2/conda-recipes-ODM2#35]
@sreeder asked me this question after last Friday's conda discussions with @ocefpaf:

> We have been discussing how we would like to package our [ODM2StreamingDataLoader](https://github.com/ODM2/ODM2StreamingDataLoader) project, and the idea of using a conda package has come up. I was under the impression that conda packaging is used for python libraries that you would be accessing from code. I am curious if using conda packaging is a viable approach for a Desktop application with a GUI. Would there be a simple way for a nearly computer illiterate user to download, “install”, and run a project that was packaged with conda?

I thought about it a bit, but don't have an answer. I've never dealt with this situation. So I'm posting it here to see what @ocefpaf and others think.

My hunch is that conda could help with the development process. Then you could use one of the Python tools to create self-contained executables (probably OS-specific) to create easy-to-install distributions (eg, [this](https://www.reddit.com/r/Python/comments/3dx91g/creating_an_exe_from_python_py2exe_nuitka_or_cx/) and [that](http://docs.python-guide.org/en/latest/shipping/freezing/)?). But this is out of my depth.

**Comment by ocefpaf** [comment]
I never did, but I think it is possible and I will look into it. (In a way miniconda and the anaconda distribution is exactly that.)

**Comment by ocefpaf** [comment]
> Would there be a simple way for a nearly computer illiterate user to download, “install”, and run a project that was packaged with conda?

Some time later I do have a clearer answer. It is possible via conda-constructor: https://www.continuum.io/blog/developer-blog/introducing-constructor

Closing this as "answered" but we can implement that when the need arises.

**Comment by sreeder** [comment]
@ocefpaf, Thanks for this update, we will keep this in mind as we get ready to release any new GUI applications!
