### ISSUE TITLE
Update odm2api

### ISSUE THREAD

**Issue by sreeder** [ODM2/conda-recipes-ODM2#42]
Update odm2api to the new v0.5.2-alpha release

**Comment by sreeder** [comment]
@ocefpaf have you had a chance to take a look at this?

**Comment by ocefpaf** [comment]
I missed this issue. Updating it now...

**Comment by emiliom** [comment]
This may be obvious based on this issue being closed, but just wanted to say explicitly that the [odm2api 0.5.2.a0](https://github.com/ODM2/ODM2PythonAPI/releases/tag/v0.5.2-alpha) conda package is now available from the odm2 anaconda.org channel. Thanks to both of you, @sreeder & @ocefpaf !

cc'ing @horsburgh and @aufdenkampe just so they know.
