### ISSUE TITLE
Packages were not uploaded when using conda-build 2

### ISSUE THREAD

**Issue by ocefpaf** [ODM2/conda-recipes-ODM2#45]
See https://github.com/SciTools/conda-build-all/pull/70

**Comment by emiliom** [comment]
Per your email, it looks like this is resolved?
https://github.com/ODM2/conda-recipes-ODM2/pull/46
https://github.com/SciTools/conda-build-all/pull/71

**Comment by ocefpaf** [comment]
It is. I was waiting for the binder update to close the issue but GitHub is [flaky today](https://twitter.com/githubstatus/status/819940738452615168).
