### ISSUE TITLE
Update Odm2api

### ISSUE THREAD

**Issue by sreeder** [ODM2/conda-recipes-ODM2#58]
Ready for a 0.5.3- alpha release.

**Comment by ocefpaf** [comment]
Can you make a release on GitHub or PyPI first? The last one is still `0.5.2-alpha`.
See https://github.com/ODM2/ODM2PythonAPI/releases

**Comment by sreeder** [comment]
sorry @ocefpaf  I forgot about that step! I will get that taken care of ASAP. I'm not sure how to create the PyPI release but I can get one created on github

**Comment by sreeder** [comment]
@ocefpaf  the release has been created in github.

**Comment by ocefpaf** [comment]
Thanks. Done in https://github.com/ODM2/conda-recipes-ODM2/pull/59

**Comment by emiliom** [comment]
Didn't realize this update was already requested and completed. Thanks to both!
