### ISSUE TITLE
ODM2API 0.6.0 release

### ISSUE THREAD

**Issue by sreeder** [ODM2/conda-recipes-ODM2#60]
Create a new ODM2API conda release.

**Comment by emiliom** [comment]
You guys are FAST with this packaging!! Thanks!

@ocefpaf, can you create a new PyPI package too? Apologies if you're already working on that; I didn't see a specific issue requesting that, and on PyPI odm2api (https://pypi.python.org/pypi/odm2api/) is still at 0.5.3

**Comment by ocefpaf** [comment]
I am working on that. I need to recover my PyPI credentials first b/c I don't have my own laptop.
