### ISSUE TITLE
udpate odm2api conda package

### ISSUE THREAD

**Issue by emiliom** [ODM2/conda-recipes-ODM2#71]
See new tagged release, v0.7.0
https://github.com/ODM2/ODM2PythonAPI/releases/tag/v0.7.0

**Comment by emiliom** [comment]
pinging @lsetiawan to keep him in the loop, since I'll be traveling

**Comment by ocefpaf** [comment]
Linux and Windows packages are already in the channel https://anaconda.org/odm2/odm2api/files?version=0.7.0.

OS X will take a while b/c Travis-CI is quite slow this past week, see https://travis-ci.org/ODM2/conda-recipes-ODM2/jobs/331274506 for the CI log.
