### ISSUE TITLE
Need conda package for ODM2RESTAPI

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/conda-recipes-ODM2#73]
Hi @ocefpaf,

We need a conda package for https://github.com/ODM2/ODM2RESTfulWebServices. Thanks.

**Comment by emiliom** [comment]
Woo-hoo! Thanks guys.

**Comment by lsetiawan** [comment]
@ocefpaf Just tested this package! Worked like a charm. THANK YOU!! 😃 

@Elijahwalkerwest heads up that this package is now on [conda](https://anaconda.org/odm2/odm2rest). Thanks.

**Comment by ocefpaf** [comment]
> @ocefpaf Just tested this package! Worked like a charm. THANK YOU!! 😃 

Thanks for testing. Let me know if you find anything amiss.
