### ISSUE TITLE
Create odm2api conda package for new release 0.7.1, on conda-forge

### ISSUE THREAD

**Issue by emiliom** [ODM2/conda-recipes-ODM2#83]
New release at https://github.com/ODM2/ODM2PythonAPI/releases/tag/v0.7.1

@ocefpaf, is the plan to continue to use this repo to request new conda packages, or should we create request issues somewhere on conda-forge? Say, for odm2api, is https://github.com/conda-forge/odm2api-feedstock the repo where we'd submit request issues?

Thanks!

cc @lsetiawan

**Comment by ocefpaf** [comment]
> @ocefpaf, is the plan to continue to use this repo to request new conda packages, or should we create request issues somewhere on conda-forge? 

That is up to you. I do prefer an issue at https://github.com/conda-forge/odm2api-feedstock/issues b/c to short circuit the communication.

PS: see https://github.com/conda-forge/odm2api-feedstock/pull/1 for the update. Also, in the near future, we won't need to send PRs like that. conda-forge has a bot to handle updates from PyPI and GitHub.

**Comment by emiliom** [comment]
> That is up to you. I do prefer an issue at https://github.com/conda-forge/odm2api-feedstock/issues b/c to short circuit the communication.

If you're doing the work, you get to tell us what you prefer! So, I'll follow your preference in the future.

> Also, in the near future, we won't need to send PRs like that. conda-forge has a bot to handle updates from PyPI and GitHub.

Cool!

Thanks for updating the odm2api conda package.
