### ISSUE TITLE
Remove packages with old names: geolachemy & odm2pythonapi

### ISSUE THREAD

**Issue by emiliom** [ODM2/conda-recipes-ODM2#9]
Now that geoalchemy-odm2 and odm2api packages have been renamed on the anaconda channel, please remove the versions with the old names: geolachemy & odm2pythonapi.

And dateutils, once we get definitive confirmation that it's not used.

**Comment by ocefpaf** [comment]
I was under the impression that I removed them yesterday. I must have done something wrong or a dangling CI build must have build the old ones. I just removed them again.

http://anaconda.org/odm2/packages

**Comment by emiliom** [comment]
They're gone now. Thanks!

**Comment by emiliom** [comment]
Please get rid of `dateutils` as well, now that we have multiple, independent confirmation it's not needed at all.

**Comment by emiliom** [comment]
Actually ... hold off on that. Let me entrain you first in another conversation about changes to requirements.txt, setup.py and pypi packaging, so we're not all wasting effort. Just leave things as is for the moment.

**Comment by ocefpaf** [comment]
No problem. I have a PR ready we can just merge/close it once we get the the confirmation.
